### ISSUE TITLE
When I try to enter $ (dollarsign) - com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V

### ISSUE THREAD

**Issue by lsv** [ivan-veselovsky/repka#3]
When I try to enter $ (dollarsign) I get this error

PHPStorm 8.0.2 139.732
JRE: 1.8.0_25.b17 AMD64

Message

```
com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
```

Details

```
com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
java.lang.NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
    at edu.jetbrains.codesense.AutoPopupTypedHandlerDelegate.schedulePopupImpl(AutoPopupTypedHandlerDelegate.java:69)
    at edu.jetbrains.codesense.AutoPopupTypedHandlerDelegate.checkAutoPopup(AutoPopupTypedHandlerDelegate.java:42)
    at com.intellij.codeInsight.editorActions.TypedHandler$1.perform(TypedHandler.java:168)
    at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:355)
    at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:435)
    at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:346)
    at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:153)
    at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:91)
    at com.intellij.openapi.editor.actionSystem.TypedAction$TypingCommand$1.run(TypedAction.java:129)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:974)
    at com.intellij.openapi.editor.actionSystem.TypedAction$TypingCommand.run(TypedAction.java:123)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:107)
    at com.intellij.openapi.editor.impl.EditorImpl.a(EditorImpl.java:1036)
    at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:5130)
    at com.intellij.openapi.editor.impl.EditorImpl$11.keyTyped(EditorImpl.java:879)
    at java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:239)
    at java.awt.Component.processKeyEvent(Component.java:6480)
    at javax.swing.JComponent.processKeyEvent(JComponent.java:2829)
    at java.awt.Component.processEvent(Component.java:6302)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
    at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
    at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
    at java.awt.Component.dispatchEventImpl(Component.java:4752)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Window.dispatchEventImpl(Window.java:2739)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:719)
    at java.awt.EventQueue$4.run(EventQueue.java:717)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:547)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ickeauch** [comment]
you probably have the extended code sense plugin installed.
try to deactivate it...

**Comment by ickeauch** [comment]
same problem with extended code sense in webstorm

**Comment by NJAldwin** [comment]
I'm seeing the same issue in IntelliJ.

**Comment by NJAldwin** [comment]
I also see the same error and stack trace when I attempt to type a digit following an alphabetic character.

**Comment by Assada** [comment]
+1
