### ISSUE TITLE
NoSuchMethodError on PhpStorm 9.0.2

### ISSUE THREAD

**Issue by Axure** [ivan-veselovsky/repka#4]
PhpStorm 9.0.2, Extended Code Sense 1.3

Occasionally when I type in some numbers, the following error shows up. The number in the problem may change.

>08:18:41 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
08:18:44 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
08:18:47 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
08:18:49 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
08:18:52 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
08:18:54 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
08:58:09 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
08:58:11 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
08:58:12 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
09:31:13 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
09:31:16 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
09:31:20 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
09:31:23 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
09:31:25 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
09:34:08 NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V

**Comment by lsv** [comment]
I can confirm this - type $

And then

```
com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
```

```
com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
java.lang.NoSuchMethodError: com.intellij.codeInsight.AutoPopupController.invokeAutoPopupRunnable(Ljava/lang/Runnable;I)V
	at edu.jetbrains.codesense.AutoPopupTypedHandlerDelegate.schedulePopupImpl(AutoPopupTypedHandlerDelegate.java:69)
	at edu.jetbrains.codesense.AutoPopupTypedHandlerDelegate.checkAutoPopup(AutoPopupTypedHandlerDelegate.java:42)
	at com.intellij.codeInsight.editorActions.TypedHandler$1.perform(TypedHandler.java:167)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:342)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:422)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:333)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:324)
	at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:152)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:91)
	at com.codeivate.plugin.keyhandlers.CodeivateTypedActionHandler.execute(CodeivateTypedActionHandler.java:60)
	at com.intellij.execution.impl.ConsoleViewImpl$MyTypedHandler.execute(ConsoleViewImpl.java:1303)
	at com.intellij.openapi.editor.actionSystem.TypedAction$TypingCommand$1.run(TypedAction.java:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.openapi.editor.actionSystem.TypedAction$TypingCommand.run(TypedAction.java:123)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:107)
	at com.intellij.openapi.editor.impl.EditorImpl.a(EditorImpl.java:1085)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:5215)
	at com.intellij.openapi.editor.impl.EditorImpl$10.keyTyped(EditorImpl.java:915)
	at java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:239)
	at java.awt.Component.processKeyEvent(Component.java:6471)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2820)
	at java.awt.Component.processEvent(Component.java:6293)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
	at java.awt.Component.dispatchEventImpl(Component.java:4742)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:539)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```
